version: "3.12"
services:
 app:
  build: .
  volumes:
   - .:/django
  ports:
   - 8000:8000
  image: yk47/floral_jamming:FloralJam
  container_name: FloralJam
  command: python manage.py runserver 0.0.0.0:8000